# Use a base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file from the build context
COPY requirements.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt 

# Copy the wait-for-it.sh script and make it executable
COPY wait-for-it.sh /app/
RUN chmod +x /app/wait-for-it.sh

# Copy the current service's code
COPY . .

# Use wait-for-it.sh to wait for the database to be ready before starting the application
ENTRYPOINT ["/app/wait-for-it.sh", "db-service:3306", "--"]

# Specify the command to run the application
CMD ["python", "app.py"]
