apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS user_db;
    CREATE DATABASE IF NOT EXISTS product_db;
    CREATE DATABASE IF NOT EXISTS order_db;
    
